/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pe.edu.cientifica.view;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pe.edu.cientifica.model.Alumno;
import pe.edu.cientifica.model.Carrera;
import pe.edu.cientifica.model.Detalle;
import pe.edu.cientifica.model.Informacion;
import pe.edu.cientifica.daoImp.AlumnoDaoImp;
import pe.edu.cientifica.daoImp.CarreraDaoImp;
import pe.edu.cientifica.daoImp.DetalleDaoImp;
import pe.edu.cientifica.daoImp.InformacionDaoImp;
/**
 *
 * @author José
 */
public class MatriculaForm extends javax.swing.JFrame {
 private AlumnoDaoImp dao = new AlumnoDaoImp();
 private CarreraDaoImp cdi = new CarreraDaoImp();
 private DetalleDaoImp ddi = new DetalleDaoImp();
 private InformacionDaoImp idi = new InformacionDaoImp();
 private DefaultTableModel model;
 private int fila=-1;
 private int idc=-1;
    /**
     * Creates new form MatriculaForm
     */
    public MatriculaForm() {
        initComponents();
        setLocationRelativeTo(null);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnguardar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        txtciclo = new javax.swing.JTextField();
        txtmodalidad = new javax.swing.JTextField();
        txtcarrera = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtfechainicio = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        btnlistar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtfechafin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtdistrito = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtdni = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbdatos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro de matricula 2023-1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel5.setText("Nombre:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel6.setText("Ciclo:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel7.setText("Modalidad:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel8.setText("Fecha Inicio:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel10.setText("Carrera:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel11.setText("Apellido:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        btnguardar.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btnguardar.setText("REGISTRAR");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        btnactualizar.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btnactualizar.setText("MODIFICAR");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        btneliminar.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btneliminar.setText("ELIMINAR");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, -1));
        jPanel1.add(txtciclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 120, -1));
        jPanel1.add(txtmodalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 120, -1));
        jPanel1.add(txtcarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 120, -1));
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 120, -1));
        jPanel1.add(txtfechainicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 119, -1));
        jPanel1.add(txtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 120, -1));

        btnlistar.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btnlistar.setText("LISTAR");
        btnlistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistarActionPerformed(evt);
            }
        });
        jPanel1.add(btnlistar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel3.setText("Fecha Fin:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));
        jPanel1.add(txtfechafin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 120, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel4.setText("Precio:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, -1, -1));
        jPanel1.add(txtprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, 120, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel9.setText("Distrito:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, -1, -1));
        jPanel1.add(txtdistrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, 120, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel12.setText("DNI:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));
        jPanel1.add(txtdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 120, -1));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel2.setText("MATRICULA 2023-1");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado de matricula", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        tbdatos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tbdatos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbdatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido", "DNI", "Distrito", "Carrera", "Ciclo", "Precio", "Fecha Inicio", "Fecha Fin", "Modalidad"
            }
        ));
        tbdatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbdatos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 854, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 854, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 854, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, 0)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        String nom = txtnombre.getText();
        String ape = txtapellido.getText();
        String cic = txtciclo.getText();
        String fechai=txtfechainicio.getText();
        String fechafi=txtfechafin.getText();
        String moda = txtmodalidad.getText();
        String carre = txtcarrera.getText();
        String dni = txtdni.getText();
        String pre = txtprecio.getText();
        String dis = txtdistrito.getText();
        if(!nom.equals("")||!ape.equals("")||!cic.equals("")||!fechai.equals("")||
            !fechafi.equals("")||!moda.equals("")||!carre.equals("")||!dni.equals("")||
            !pre.equals("")||!dis.equals("")){
            dao.create(new Alumno(0,nom,ape,cic));
            cdi.create(new Carrera(0 ,carre));
            ddi.create(new Detalle(0,pre,fechai,fechafi,moda));
            idi.create(new Informacion(0,dis,dni));
            limpiar_table();
            limpiar();
            JOptionPane.showMessageDialog(rootPane, "El alumno se a registrado Correctamente...!");
        }else{
            JOptionPane.showMessageDialog(rootPane, "Campos Vacios");
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        String nom = txtnombre.getText();
        String ape = txtapellido.getText();
        String cic = txtciclo.getText();
        String fechai=txtfechainicio.getText();
        String fechafi=txtfechafin.getText();
        String moda = txtmodalidad.getText();
        String carre = txtcarrera.getText();
        String dni = txtdni.getText();
        String pre = txtprecio.getText();
        String dis = txtdistrito.getText();
        if(fila>=0){
            int result = JOptionPane.showConfirmDialog(this,"Realmente desea modificar el Registro?", "Swing Tester",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
            if(result == JOptionPane.YES_OPTION){
                dao.update(new Alumno(idc, nom, ape, cic));
                cdi.update(new Carrera(idc, carre));
                ddi.update(new Detalle(idc, pre, fechai, fechafi, moda));
                idi.update(new Informacion(idc, dis, dni));
                limpiar_table();
                listar();
                limpiar();
                JOptionPane.showMessageDialog(rootPane, "Se ha Actualizado Correctamente...!");
            }else if (result == JOptionPane.NO_OPTION){
                JOptionPane.showMessageDialog(rootPane, "No se ha Actualizado el Registro");
            }else {

            }

        }else{
            JOptionPane.showMessageDialog(rootPane, "Seleccionar la Fila");
        }
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        if(fila>=0){
            int result = JOptionPane.showConfirmDialog(this,"Realmente desea eliminar el Registro?", "Swing Tester",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
            if(result == JOptionPane.YES_OPTION){
                dao.delete(idc);
                cdi.delete(idc);
                ddi.delete(idc);
                idi.delete(idc);
                limpiar_table();
                listar();
                limpiar();
                JOptionPane.showMessageDialog(rootPane, "Se ha eliminado Correctamente...!");
            }else if (result == JOptionPane.NO_OPTION){
                JOptionPane.showMessageDialog(rootPane, "No se ha Eliminado el Registro");
            }else {

            }

        }else{
            JOptionPane.showMessageDialog(rootPane, "Seleccionar la Fila");
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnlistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistarActionPerformed
        listar();
    }//GEN-LAST:event_btnlistarActionPerformed

    private void tbdatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdatosMouseClicked
        fila = tbdatos.getSelectedRow();
        idc = Integer.parseInt(tbdatos.getValueAt(fila, 0).toString());
        txtnombre.setText(tbdatos.getValueAt(fila, 1).toString());
        txtapellido.setText(tbdatos.getValueAt(fila, 2).toString());
        txtdni.setText(tbdatos.getValueAt(fila, 3).toString());
        txtdistrito.setText(tbdatos.getValueAt(fila, 4).toString());
        txtcarrera.setText(tbdatos.getValueAt(fila, 5).toString());
        txtciclo.setText(tbdatos.getValueAt(fila, 6).toString());
        txtprecio.setText(tbdatos.getValueAt(fila, 7).toString());
        txtfechainicio.setText(tbdatos.getValueAt(fila, 8).toString());
        txtfechafin.setText(tbdatos.getValueAt(fila, 9).toString());
        txtmodalidad.setText(tbdatos.getValueAt(fila, 10).toString());
    }//GEN-LAST:event_tbdatosMouseClicked

    private void listar(){
        limpiar_table();
        model = (DefaultTableModel)tbdatos.getModel();
        List<Alumno> lista = dao.readAll();
        List<Carrera> lista1 = cdi.readAll();
        List<Detalle> lista2 = ddi.readAll();
        List<Informacion> lista3=idi.readAll();
        Object datos[] =new Object[11];
        for(int i=0;i<lista.size();i++){
            datos[0]=lista.get(i).getIdalumno();
            datos[1]=lista.get(i).getNombre();
            datos[2]=lista.get(i).getApellido();
            datos[3]=lista3.get(i).getDni();
            datos[4]=lista3.get(i).getDistrito();
            datos[5]=lista1.get(i).getCarre();
            datos[6]=lista.get(i).getCiclo();
            datos[7]=lista2.get(i).getPrecio();
            datos[8]=lista2.get(i).getFechainicio();
            datos[9]=lista2.get(i).getFechafinal();
            datos[10]=lista2.get(i).getModalidad();
            
            model.addRow(datos);
        }
        tbdatos.setModel(model);
    }
    private void limpiar_table(){
        for(int i=0;i<tbdatos.getRowCount();i++){
            model.removeRow(i);
            i=-1;
        }
    }
    private void limpiar(){
        txtnombre.setText(null);
        txtapellido.setText(null);
        txtciclo.setText(null);
        txtfechainicio.setText(null);
        txtfechafin.setText(null);
        txtmodalidad.setText(null);
        txtprecio.setText(null);
        txtdni.setText(null);
        txtdistrito.setText(null);
        txtcarrera.setText(null);
        txtnombre.requestFocus();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MatriculaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MatriculaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MatriculaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MatriculaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MatriculaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnlistar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbdatos;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtcarrera;
    private javax.swing.JTextField txtciclo;
    private javax.swing.JTextField txtdistrito;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtfechafin;
    private javax.swing.JTextField txtfechainicio;
    private javax.swing.JTextField txtmodalidad;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtprecio;
    // End of variables declaration//GEN-END:variables
}
